using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SwordStrike: MonoBehaviour
{
    //Player projectile generated by the Weapon class
    
    public float speed = 20f;
    public int damage = 1;
    public Rigidbody2D rb;
    public float lifeTime = 0.07f;

    void Start()
    {
        rb = gameObject.GetComponent<Rigidbody2D>();
        rb.velocity = transform.up * speed;
        StartCoroutine("LifeTime");
    }

    void OnTriggerEnter(Collider hitInfo)
    { 
        
    }

    IEnumerator LifeTime()
    {
        yield return new WaitForSeconds(lifeTime);
        Destroy(gameObject);
    }
}
